.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. jumpcoin_qt test_jumpcoin_qt
clean: FORCE
	$(MAKE) -C .. jumpcoin_qt_clean test_jumpcoin_qt_clean
check: FORCE
	$(MAKE) -C .. test_jumpcoin_qt_check
jumpcoin-qt jumpcoin-qt.exe: FORCE
	 $(MAKE) -C .. jumpcoin_qt
